# Usa a imagem oficial do n8n
FROM n8nio/n8n:latest

# Define o diretório de trabalho dentro do container
WORKDIR /data

# Copia variáveis de ambiente se houver um arquivo .env
COPY .env .env

# Expõe a porta padrão do n8n
EXPOSE 5678

# Comando padrão para iniciar o n8n
CMD ["n8n", "start"]
